### ISSUE TITLE
Infer error

### ISSUE THREAD

**Issue by willright28** [lntran26/donni#24]
Hi @lntran26 and all contributors!

I find the donni is very interesting and useful! I've tried to train a custom model following your instructions and it seems work well! But when I tried to infer my population history with the custom model, error message reported: 

```
Traceback (most recent call last):
  File "/home/song/miniconda3/envs/donni/bin/donni", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/donni/__main__.py", line 455, in main
    args.func(args)
  File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/donni/__main__.py", line 121, in run_infer
    pred, theta, cis = infer(filename_list, args.mlpr_dir, 
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/donni/infer.py", line 179, in infer
    mean, var = mlpr.predict(np.array(input_x))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_file9s_omqlq.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
    ^^^^^
ValueError: in user code:

    File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/keras/engine/training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/keras/engine/training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/keras/engine/training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/keras/engine/training.py", line 2111, in predict_step
        return self(x, training=False)
    File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/home/song/miniconda3/envs/donni/lib/python3.11/site-packages/keras/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "model_1" is incompatible with the layer: expected shape=(None, 9261), found shape=(None, 68921)
```

Here is the code I used:
```
donni generate_data --model split_asym_mig_adjacent_var1 --model_file split_asym_mig_adjacent_var1.py \
	--n_samples 5000 \
	--sample_sizes 20 20 20 \
	--outfile data/train_5000 --seed 1 \
	--n_cpu 40

donni generate_data --model split_asym_mig_adjacent_var1 --model_file split_asym_mig_adjacent_var1.py --n_samples 1000 \
	--sample_sizes 20 20 20 --seed 1 --theta 1000 --outfile data/test_1000_theta_1000 --n_cpu 40
	
donni train --data_file data/train_5000 --mlpr_dir trained_models  --tune

donni train --data_file data/train_5000 --mlpr_dir trained_models

donni validate --model split_asym_mig_adjacent_var1 --model_file split_asym_mig_adjacent_var1.py \
	--mlpr_dir /disk1/chenyilin/sparrow/donni/CN_EU_MD/trained_models \
	--test_dict /disk1/chenyilin/sparrow/donni/CN_EU_MD/data/test_1000_theta_1000 \
	--results_dir /disk1/chenyilin/sparrow/donni/CN_EU_MD/validate/ --plot_prefix split_asym_mig_adjacent_var1_theta_1000

donni infer --input_fs China-Europe-Central_Asia.sfs --model split_asym_mig_adjacent_var1 \
	--model_file split_asym_mig_adjacent_var1.py \
	--mlpr_dir /disk1/chenyilin/sparrow/donni/CN_EU_MD/trained_models \
	--output_prefix ./output/adj_asym --export_dadi_cli ./output/adj_asym.dadi.cli
```
The fs and custom model I trained was based on unfold sfs, but my own input was a folded sfs. I wonder if that has anything to do with it?

The attachments are my model.py and validate report.

Many thanks for your attention and time!

Best,
willright28
[willright28_donni.zip](https://github.com/user-attachments/files/17533634/willright28_donni.zip)

**Comment by lntran26** [comment]
Hi @willright28 , 
Thanks for reaching out. I haven't looked at your code and the error message closely but re your question near the end: yes, you will indeed need to train the custom model using folded sfs instead if the input data you wish to use is a folded sfs. You should be able to generate simulated folded sfs for training using the flag `--folded` added to the `generate_data` commands for generating both the train and test sets. All the following steps can be kept as is. Please try this and follow up here if you still have problems.

**Comment by willright28** [comment]
Hi @lntran26,

Thanks for reply!
I have re-generated the folded sfs. And the donni infer worked well! But it seems still have a problem, about the sample size. In your mannul said: "Input allele frequency spectra with a different sample size will be automatically down-projected to the closest available supported size before inference". I modeled a three populations situation and the simulated sfs was 10 10 10, when I inputted a larger sample size sfs, say 200 160 150, the infer returned error message as I reported above and I have to down-projected my sfs manully using `dadi-cli GenerateFs --projections 10 10 10`. So is there anything incorrectly in my code to using a larger sfs as input?

**Comment by lntran26** [comment]
Hi @willright28 ,
The statement you quoted about automatic down-projection only applies to models that we already trained and provided through our library. Because we can only provide trained models for a limited set of sample sizes and the sample size of users' data can vary a lot, we provide the automatic down-projection to keep donni's trained models relatively accessible. Since you are training your own model, we assume that you would train using the sample size that would be appropriate for your data so the pipeline won't do any automatic projection. Instead it should expect an exact match between your provided trained model and input data. So the error you described is expected and I don't think that indicates anything wrong with your code. I'm glad you were able to use `dadi-cli` to down-project your data, though projecting from `200 160 150` to `10 10 10` seems very drastic to me.

**Comment by willright28** [comment]
Hi @lntran26 ,

Many thanks for solving the questions! I will try to figure out a suitable number of down-projection of my data.
